export const mycroftUrl = 'https://mycroftproject.com/installos.php/';
export const bingUrl = 'https://www.bing.com/visualsearch';
export const ddgUrl = 'https://icons.duckduckgo.com/ip3/';
export const horseIconUrl = 'https://icon.horse/icon/';
export const googleReverseImageSearchUrl = 'https://www.google.com/searchbyimage?sbisrc=1&safe=off&image_url=';
export const googleLensUrl = 'https://lens.google.com/uploadbyurl?url=';
export const tineyeUrl = 'https://www.tineye.com';
export const chatGPTUrl = 'https://chatgpt.com';
export const googleAIStudioUrl = 'https://aistudio.google.com/app/prompts/new_chat';
export const grokUrl = 'https://grok.com';
export const perplexityAIUrl = 'https://www.perplexity.ai';
export const poeUrl = 'https://poe.com';
export const claudeUrl = 'https://claude.ai';
export const andiUrl = 'https://andisearch.com';
export const aiUrls = [chatGPTUrl, googleAIStudioUrl, grokUrl, perplexityAIUrl, poeUrl, claudeUrl, andiUrl];